version: '3'
services:
  db:
    container_name: "database"
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=social
    ports:
      - '5432:5432'

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8000:8000'